# Generated by Django 5.1.2 on 2025-02-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaded_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_id', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('encrypted_paths', models.TextField()),
                ('encrypted_password', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CountModel',
        ),
        migrations.DeleteModel(
            name='MyImageModel',
        ),
    ]
