# Generated by Django 5.1.6 on 2025-03-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uploadedpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('random_id', models.CharField(max_length=200, unique=True)),
                ('key', models.CharField(max_length=200)),
                ('encrypted_paths', models.TextField()),
                ('encrypted_password', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.CharField(max_length=10)),
                ('split_files', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
